export const DICTIONARY_OBJCECT_REQUEST = "DICTIONARY_OBJCECT_REQUEST";
export const DICTIONARY_OBJCECT_SUCCESS = "DICTIONARY_OBJCECT_SUCCESS";
export const DICTIONARY_OBJCECT_FAIL = "DICTIONARY_OBJCECT_FAIL";